[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"

[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
